[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py runserver 0.0.0.0:8000"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
