[build]
builder = "NIXPACKS"

[build.env]
PYTHON_VERSION = "3.10"

[deploy]
start = "python manage.py migrate && gunicorn social_project.wsgi:application --bind 0.0.0.0:8000"
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10