# Generated by Django 5.0.7 on 2024-07-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hola, twitter', max_length=100),
        ),
    ]
