# Generated by Django 5.0.7 on 2024-07-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_alter_post_id_alter_profile_id_alter_relationship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
